### ISSUE TITLE
This is not an issue, but it's not available for my school. I would love for it to be available! <3

### ISSUE THREAD

**Issue by renoshinnosuke** [marissarousseau/canvasdarkmode#21]
Hi, is there any way for this extension to be available for my university? University of Auckland in New zealand. Thank you for your time!

**Comment by marissarousseau** [comment]
Hi there! Thanks for your comments. I haven't had a lot of time to work on the extension as of late because of everything going on with the pandemic and my schedule being a bit of a mess. I hope to get back to working on it soon as I want to redesign the whole thing from scratch to remove bugs and better support for many institutions. 

In the meantime, could you post the link that shows in the address bar when you are viewing the Dashboard page on Canvas? I will need it later on once I pick this project back up.

**Comment by renoshinnosuke** [comment]
Hello marissa! Thank you for the reply! No rush and no worries, i hope everything is going well for you. Whenever you do pick back up the project, here is the link ^_^ https://canvas.auckland.ac.nz/ 
Cheers!

**Comment by marissarousseau** [comment]
Thank you! I have taken note of your organization's URL. I'm now closing this issue, see #20.
